# This task is used to update the main and env branches with
# image tags from the promoted image.
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: render-image
  namespace: kargo-rendered-branches
spec:
  vars:
  - name: repoURL
    value: https://github.com/jessesuen/kargo-rendered-branches.git
  - name: image
    value: ghcr.io/jessesuen/guestbook
  - name: branch
    value: main
  - name: stage
    value: ${{ ctx.stage }}
  steps:
  # Clone the unrendered, templated config in main branch to ./main
  # and the env-specific rendered branch to ./out.
  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - branch: ${{ vars.branch }}
        path: ./main
      - branch: env/${{ vars.stage }}
        path: ./out
        create: true

  # Update env/<stage>/values-image.yaml with the promoted image tag
  # Then commit and push the changes to main
  - uses: yaml-update
    config:
      path: ./main/env/${{ vars.stage }}/values-image.yaml
      updates:
      - key: image.tag
        value: ${{ imageFrom( vars.image ).Tag }}
  - uses: git-commit
    as: commit
    config:
      path: ./main
      message: ${{ 'Update ' + vars.stage + ' to ' + imageFrom(vars.image).Tag }}
  - uses: git-push
    config:
      path: ./main

  # Render the configuration to the env-specific branch.
  # Then commit and push the changes
  - uses: git-clear
    config:
      path: ./out
  - uses: helm-template
    config:
      path: ./main/charts/guestbook
      releaseName: guestbook
      useReleaseName: false
      valuesFiles:
      - ./main/env/${{ vars.stage }}/values-image.yaml
      - ./main/env/${{ vars.stage }}/values.yaml
      outPath: ./out
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: ${{ 'Update ' + vars.stage + ' to ' + imageFrom(vars.image).Tag }}
  - uses: git-push
    config:
      path: ./out
