---
# Source: guestbook/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: guestbook
  labels:
    helm.sh/chart: guestbook-0.1.0
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/instance: guestbook
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/instance: guestbook
